// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ParkingSystem_NTTDigital.Data;

#nullable disable

namespace ParkingSystem_NTTDigital.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20230305161956_initial")]
    partial class initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0-preview.1.23111.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ParkingSystem_NTTDigital.Entities.LotDetail", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("LotNumberId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Plat")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("TimeIn")
                        .HasColumnType("datetime2");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LotNumberId");

                    b.HasIndex("Plat")
                        .IsUnique();

                    b.ToTable("lot_detail");
                });

            modelBuilder.Entity("ParkingSystem_NTTDigital.Entities.LotNumber", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<int>("number")
                        .HasColumnType("int")
                        .HasColumnName("number");

                    b.HasKey("Id");

                    b.ToTable("lot_number");
                });

            modelBuilder.Entity("ParkingSystem_NTTDigital.Entities.LotDetail", b =>
                {
                    b.HasOne("ParkingSystem_NTTDigital.Entities.LotNumber", "LotNumber")
                        .WithMany()
                        .HasForeignKey("LotNumberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LotNumber");
                });
#pragma warning restore 612, 618
        }
    }
}
